.github/workflows/test.yml
.github/workflows/testacc.yml

This PR to make a special workflow for acceptance tests.
It require a slash-command in a comment : /testacc
Acceptance Tests are played only if a OWNER or MEMBER comment the PR with this slash-command.

ci: play acceptance tests only with slash command

---

docs/data-sources/vdc.md
internal/provider/vdc_datasource.go
internal/provider/vdc_datasource_test.go

Change datasource vdc schema according to vdc ressource
```
❯ make testacc TEST=./internal/provider TESTARGS='-run TestAccVdcDataSource'
TF_ACC=1 go test ./... -v -run TestAccVdcDataSource -timeout 120m
?       github.com/orange-cloudavenue/terraform-provider-cloudavenue    [no test files]
=== RUN   TestAccVdcDataSource
--- PASS: TestAccVdcDataSource (9.79s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/provider  9.793s
testing: warning: no tests to run
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/pkg/utils  (cached) [no tests to run]
```

feat(vdc): change datasource schema

---

go.mod
go.sum
internal/helpers/stringpm/README.md
internal/helpers/stringpm/default.go
internal/helpers/stringpm/default_test.go

Close #55
```
ok  	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/helpers/stringpm	0.413s
```

chore(helper): add helper stringpm `Default` (#55)

---

internal/helpers/stringpm/README.md
internal/helpers/stringpm/base_default_func.go
internal/helpers/stringpm/default.go
internal/helpers/stringpm/default_env_var.go
internal/helpers/stringpm/default_env_var_test.go
internal/helpers/stringpm/default_func.go
internal/helpers/stringpm/default_func_test.go
internal/helpers/stringpm/default_test.go

Close #65 
```
go test -count=1 -v ./internal/helpers/stringpm/
=== RUN   TestDefaultEnvVarModifierPlanModifyString
=== RUN   TestDefaultEnvVarModifierPlanModifyString/null-state
=== RUN   TestDefaultEnvVarModifierPlanModifyString/known-plan
=== RUN   TestDefaultEnvVarModifierPlanModifyString/non-null-state-unknown-plan
=== RUN   TestDefaultEnvVarModifierPlanModifyString/unknown-config
--- PASS: TestDefaultEnvVarModifierPlanModifyString (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyString/null-state (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyString/known-plan (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyString/non-null-state-unknown-plan (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyString/unknown-config (0.00s)
=== RUN …
```

chore(helper): add PlanModifierString `SetDefaultFunc`

---

internal/helpers/boolpm/README.md
internal/helpers/boolpm/base_default_func.go
internal/helpers/boolpm/default.go
internal/helpers/boolpm/default_env_var.go
internal/helpers/boolpm/default_env_var_test.go
internal/helpers/boolpm/default_func.go
internal/helpers/boolpm/default_func_test.go
internal/helpers/boolpm/default_test.go

Close #74 
```
go test -count=1 -v ./internal/helpers/boolpm/
=== RUN   TestDefaultEnvVarModifierPlanModifyBool
=== RUN   TestDefaultEnvVarModifierPlanModifyBool/null-state
=== RUN   TestDefaultEnvVarModifierPlanModifyBool/known-plan
=== RUN   TestDefaultEnvVarModifierPlanModifyBool/non-null-state-unknown-plan
=== RUN   TestDefaultEnvVarModifierPlanModifyBool/unknown-config
--- PASS: TestDefaultEnvVarModifierPlanModifyBool (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyBool/null-state (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyBool/known-plan (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyBool/non-null-state-unknown-plan (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyBool/unknown-config (0.00s)
=== RUN   TestDefaultFuncModifierPlanModifyBool
=== RUN …
```

chore(helper): add PlanModifier boolean `SetDefault...` 

---

.github/workflows/test.yml

Restrict the Lint Job on PR on main branch when Go or examples files have been modified.

ci: restrict lint and generate diff on PR

---

docs/resources/vapp_vm_internal_disk.md
examples/resources/cloudavenue_vapp_vm_internal_disk/resource.tf
internal/provider/vapp/vm_internal_disk_resource.go
internal/tests/vapp_vm_internal_disk_resource_test.go

```
=== RUN   TestAccVMInternalDiskResource
--- PASS: TestAccVMInternalDiskResource (37.28s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests     37.397s
```

refactor(vapp): replace deprecated Blocks

---

internal/provider/vapp/org_network_resource.go
internal/tests/vapp/org_network_resource_test.go

```
❯ TF_ACC=1 go test -v -count=1  -run TestAccOrgNetworkResource  ./internal/tests/vapp
=== RUN   TestAccOrgNetworkResource
--- PASS: TestAccOrgNetworkResource (17.02s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vapp        17.315s
```

fix(vapp): bad import on org_network_resource if VDC is in the ID

---

docs/data-sources/edgegateway.md
docs/data-sources/edgegateways.md
docs/resources/edgegateway.md
examples/data-sources/cloudavenue_edgegateway/data-source.tf
examples/resources/cloudavenue_edgegateway/import.sh
internal/provider/edgegw/edgegateway_datasource.go
internal/provider/edgegw/edgegateway_resource.go
internal/provider/edgegw/edgegateways_datasource.go
internal/tests/edgegw/edgegateway_datasource_test.go
internal/tests/edgegw/edgegateway_resource_test.go
internal/tests/edgegw/edgegateways_datasource_test.go

Replace `edge_id` by `id` (with urn id), and `edge_name` by `name` in all edgegateway objects
Play with Terraform and acceptance tests : 
```
❯ TF_ACC=1 go test -v -count=1 ./internal/tests/edgegw
=== RUN   TestAccEdgeGatewayDataSource
--- PASS: TestAccEdgeGatewayDataSource (5.96s)
=== RUN   TestAccEdgeGatewayResource
--- PASS: TestAccEdgeGatewayResource (136.73s)
=== RUN   TestAccEdgeGatewaysDataSource
--- PASS: TestAccEdgeGatewaysDataSource (6.60s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw      149.297s
```

feat(edge): review id and name attributes 

---

docs/resources/publicip.md
examples/resources/cloudavenue_publicip/resource.tf
internal/provider/publicip/publicip_resource.go

`edge_id` is now a complete URN ID instead of an UUID.

fix(publicip): edge_id is now a complete URN ID

---

internal/provider/common/acl/acl.go
internal/provider/vapp/acl_resource.go
internal/provider/vdc/acl_resource.go
internal/tests/vapp/acl_resource_test.go

- Add SharedSetToAccessControl and AccessControlListToSharedSet functions to common/acl
- Use it in vapp_acl
- Uniformise vapp_acl and vdc_acl
```
❯ TF_ACC=1 go test -run TestAccACLResource -v -count=1 ./internal/tests/vapp
=== RUN   TestAccACLResource
--- PASS: TestAccACLResource (10.38s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vapp        10.384s
❯ TF_ACC=1 go test -run TestAccACLResource -v -count=1 ./internal/tests/vdc 
=== RUN   TestAccACLResource
--- PASS: TestAccACLResource (9.26s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vdc 9.268s
```

refactor: add common acl func

---

docs/resources/edgegateway.md
docs/resources/vapp_org_network.md
examples/resources/cloudavenue_edgegateway/resource.tf
examples/resources/cloudavenue_vapp_org_network/resource.tf
internal/provider/edgegw/edgegateway_resource.go
internal/tests/edgegw/edgegateway_resource_test.go
internal/tests/vapp/org_network_resource_test.go

- Test vdc or vdc-group existance before create the edgegateway
- Add better testing
```
❯ TF_ACC=1 go test -v -count=1 ./internal/tests/edgegw -run TestAccEdgeGatewayResource
=== RUN   TestAccEdgeGatewayResource
--- PASS: TestAccEdgeGatewayResource (336.21s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw      336.219s
```

fix(edgegw): test vdc existance before create 

---

internal/provider/network/common_network.go
internal/provider/network/routed_resource.go

refactor(network): remove diagnosticError struct and use diag.Diagnostic

---

internal/client/vmware.go
internal/provider/common/vapp/vapp.go
internal/provider/common/vdc/vdc.go
internal/provider/common/vm/disk.go
internal/provider/common/vm/internal_disk.go
internal/provider/network/routed_resource.go
internal/provider/vapp/org_network_resource.go
internal/provider/vapp/vapp_resource.go
internal/provider/vdc/acl_resource.go
internal/provider/vm/common_vm.go
internal/provider/vm/common_vm_create.go
internal/provider/vm/common_vm_read.go
internal/provider/vm/common_vm_update.go
internal/provider/vm/vm_resource.go

Tests OK :
```
❯ TF_ACC=1 go test -v -count=1  -run TestAccNetworkRoutedResource  ./internal/tests/network
=== RUN   TestAccNetworkRoutedResource
--- PASS: TestAccNetworkRoutedResource (79.22s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/network     79.623s
```
```
❯ TF_ACC=1 go test -v -count=1  -run TestAccVappResource  ./internal/tests/vapp
=== RUN   TestAccVappResource
--- PASS: TestAccVappResource (21.66s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vapp        22.099s
```

feat(vdc): add interface to handle vdc or vdc group

---

docs/resources/network_routed.md
examples/resources/cloudavenue_network_routed/resource.tf
internal/provider/network/routed_resource.go
internal/tests/network/routed_resource_test.go

```
❯ TF_ACC=1 go test -v -count=1  -run TestAccNetworkRoutedResource  ./internal/tests/network
=== RUN   TestAccNetworkRoutedResource
--- PASS: TestAccNetworkRoutedResource (225.85s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/network     226.408s
```

fix(network): cloudavenue_network_routed error on import

---

internal/provider/vapp/isolated_network_resource.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Add StringValueOrNull  function and use it in vapp_isolated_network
```
❯ TF_ACC=1 go test -v -count=1  -run TestAccIsolatedNetworkResource  ./internal/tests/vapp
=== RUN   TestAccIsolatedNetworkResource
--- PASS: TestAccIsolatedNetworkResource (30.06s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vapp        30.069s
❯ go test -v -count=1  -run TestStringValueOrNull ./pkg/utils/
=== RUN   TestStringValueOrNull
=== RUN   TestStringValueOrNull/StringValue
=== RUN   TestStringValueOrNull/StringNull
--- PASS: TestStringValueOrNull (0.00s)
--- PASS: TestStringValueOrNull/StringValue (0.00s)
--- PASS: TestStringValueOrNull/StringNull (0.00s)
PASS
ok …
```

feat: add StringValueOrNull function

---

docs/resources/vm_affinity_rule.md
internal/provider/vm/vm_affinity_rule_schema.go

Fixe #207 
```
TF_ACC=1 go test -v -count=1  -run TestAccVmAffinityRuleResource  ./internal/tests/vm
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vm  41.814s
```

refactor: use superschema for the vm_affinity_rule resource

---

docs/index.md
internal/provider/common/cloudavenue/cloudavenue.go
internal/provider/edgegw/edgegateway_resource.go
internal/provider/publicip/publicip_resource.go
internal/provider/vcda/vcda_ip_resource.go
internal/provider/vdc/vdc_resource.go
templates/index.md.tmpl

Fixe #211 
```
cloudavenue_edgegateway.example_with_vdc: Creating...
cloudavenue_vdc.example: Creating...
cloudavenue_vdc.example: Still creating... [10s elapsed]
cloudavenue_edgegateway.example_with_vdc: Still creating... [10s elapsed]
cloudavenue_edgegateway.example_with_vdc: Still creating... [20s elapsed]
cloudavenue_vdc.example: Still creating... [20s elapsed]
cloudavenue_vdc.example: Still creating... [30s elapsed]
cloudavenue_edgegateway.example_with_vdc: Still creating... [30s elapsed]
cloudavenue_vdc.example: Still creating... [40s elapsed]
cloudavenue_edgegateway.example_with_vdc: Still creating... [40s elapsed]
cloudavenue_vdc.example: Still creating... [50s elapsed]
cloudavenue_edgegateway.example_with_vdc: Still …
```

chore: Add lock/unlock for customer API

---

.ci/scripts/release-note.tmpl
.github/workflows/dapendabot_changelog.yml
.github/workflows/generate_changelog.yml
CHANGELOG.md
CONTRIBUTING.md

Fix CHANGELOG generation by using a PAT to push on main branch
Add the unreleased version in CHANGELOG.md
Rewrite the release-note template

ci: fix generate-changelog

---

.changelog/320.txt
docs/resources/vm.md
examples/resources/cloudavenue_vm/import.sh
internal/provider/common/vm/settings.go
internal/provider/common/vm/settings_customization.go
internal/provider/common/vm/settings_guest_properties.go
internal/provider/vm/vm_resource.go
internal/provider/vm/vm_schema.go
internal/tests/vm/vm_resource_test.go

feat: add import for `cloudavenue_vm`

---

.goreleaser.yml

Try to fix the generation of release note in GitHub Release.
According to the [documentation](https://goreleaser.com/customization/changelog/), it seems that in recent goreleaser version, the changelog Skip: True provide an empty release not in GitHub Release.

ci: fix goreleaser to generate changelog in release

---

.changelog/347.txt
docs/resources/edgegateway_app_port_profile.md
examples/resources/cloudavenue_edgegateway_app_port_profile/import.sh
examples/resources/cloudavenue_edgegateway_app_port_profile/resource.tf
examples/resources/cloudavenue_network_app_port_profile/import.sh
internal/provider/edgegw/app_port_profile_resource.go
internal/provider/provider.go
internal/tests/edgegw/app_port_profile_resource_test.go
templates/resources/edgegateway_app_port_profile.md.tmpl

```
TF_ACC=1 go test -v ./internal/tests/edgegw/ -run TestAccPortProfilesResource
=== RUN   TestAccPortProfilesResource
--- PASS: TestAccPortProfilesResource (52.93s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/edgegw      53.262s
```

fix: Change resource `cloudavenue_network_app_port_profile` to `cloudavenue_edgegateway_app_port_profile` 

---

.changelog/380.txt
docs/data-sources/vm_affinity_rule.md
docs/resources/vm_affinity_rule.md
internal/provider/vm/vm_affinity_rule_datasource.go
internal/provider/vm/vm_affinity_rule_resource.go
internal/provider/vm/vm_affinity_rule_schema.go
internal/tests/vm/vm_affinity_rule_resource_test.go
templates/resources/vm_affinity_rule.md.tmpl

Fixes #380 
```
TF_ACC=1 go test -v -count=1 -timeout 600m github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vm/vm_affinity_rule_resource_test.go
=== RUN   TestAccVmAffinityRuleResource
--- PASS: TestAccVmAffinityRuleResource (452.24s)
PASS
ok      command-line-arguments  452.903s
```

fix: `resource/cloudavenue_vm_affinity_rule` - Set more than 2VMs IDs

---

internal/provider/publicip/publicip_resource.go
internal/tests/publicip/publicip_resource_test.go

```
TF_ACC=1 go test -v -count=1 -timeout 600m /Users/micheneaudavid/go/src/github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/publicip/publicip_resource_test.go
=== RUN   TestAccPublicIPResource
--- PASS: TestAccPublicIPResource (112.97s)
PASS
ok      command-line-arguments  113.283s
```

fix: bug new cloudavenue publicip return wrong public ip

---

.changelog/407.txt
docs/resources/iam_user.md
docs/resources/vapp.md
docs/resources/vapp_acl.md
docs/resources/vapp_org_network.md
examples/resources/cloudavenue_iam_user/resource.tf
examples/resources/cloudavenue_vapp/resource.tf
examples/resources/cloudavenue_vapp_acl/resource.tf
examples/resources/cloudavenue_vapp_org_network/resource.tf
internal/provider/vapp/acl_resource.go
internal/provider/vapp/acl_schema.go
internal/tests/iam/iam_user_datasource_test.go
internal/tests/iam/iam_user_resource_test.go
internal/tests/vapp/acl_resource_test.go
internal/tests/vapp/org_network_resource_test.go
internal/tests/vapp/vapp_resource_test.go

Fix units tests for Vapp Resources. 
```
=== RUN   TestAccUserResource
--- PASS: TestAccUserResource (19.82s)
PASS
ok      command-line-arguments  20.394s
```
```
=== RUN   TestAccUserDataSource
--- PASS: TestAccUserDataSource (23.36s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/iam 23.948s
```
```
=== RUN   TestAccACLResource
--- PASS: TestAccACLResource (43.17s)
PASS
ok      command-line-arguments  43.736s
``` 
```
=== RUN   TestAccVappResource
--- PASS: TestAccVappResource (50.06s)
PASS
ok      command-line-arguments  50.432s
```
```
=== RUN   TestAccOrgNetworkResource
--- PASS: TestAccOrgNetworkResource (231.67s)
PASS
ok      command-line-arguments  232.230s
```

fix: `cloudavenue_vapp_*` units tests and improve example

---

.changelog/462.txt
go.mod
go.sum

Reverts orange-cloudavenue/terraform-provider-cloudavenue#462

fix: Revert bump hashicorp/terraform-plugin-framework-validators from 0.10.0 to 0.11.0

---

.changelog/511.txt
go.mod
internal/provider/vdc/vdc_resource.go

```
TF_ACC=1 go test -v -count=1 -timeout 30m -run TestAccVDCResource
```

fix: error VDC group name cannot be update in vcd resource

---

.changelog/518.txt
go.mod
go.sum
internal/provider/vdc/vdc_resource.go

Fix bug to impossible to update a vcd resource without a resource vcd_group define

fix: bug to impossible to update a vcd resource without a resource vcd_group define

---

.changelog/521.txt
internal/provider/vdc/vdc_resource.go
internal/testsacc/vdc_resource_test.go

Fix bug for vdc update in relation ship with field vdcgroup or resource vdc_group
Fix vdc test acc
```TF_ACC=1 go test -v ./internal/testsacc/ -count=1 -timeout 30m -run TestAccVDCResource
--- PASS: TestAccVDCResource (94.01s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  94.379s
```

fix: update testacc vdcgroup and vdc resource

---

.changelog/526.txt
docs/resources/network_routed.md
examples/resources/cloudavenue_network_routed/import.sh
internal/helpers/testsacc/testsacc.go
internal/provider/network/routed_resource.go
internal/testsacc/acctest.go
internal/testsacc/network_routed_resource_test.go

```
TF_ACC=1 go test -v ./internal/testsacc/ -count=1 -timeout 30m -run TestAccNetworkRoutedResource
=== RUN   TestAccNetworkRoutedResource
--- PASS: TestAccNetworkRoutedResource (374.86s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  375.171s
```

feat: Change attribute field for import resource by EdgeGatewayName or EdgeGatewayID. (#525)

---

.changelog/538.txt
docs/data-sources/vapp_org_network.md
docs/resources/vapp_org_network.md
internal/provider/common/network/schema.go
internal/provider/vapp/org_network_datasource.go
internal/provider/vapp/org_network_resource.go
internal/provider/vapp/vapp_types.go
internal/testsacc/acctest.go
internal/testsacc/vapp_org_network_datasource_test.go
internal/testsacc/vapp_org_network_resource_test.go

```
=== RUN   TestAccOrgNetworkResource
--- PASS: TestAccOrgNetworkResource (488.83s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  489.398s
```

fix!: remove attributs `is_fenced` and `retain_ip_mac_enabled`

---

internal/helpers/testsacc/template.go
internal/helpers/testsacc/testsacc.go
internal/testsacc/acctest.go
internal/testsacc/vdc_datasource_test.go

Fix #543 
```
=== RUN   TestVDCDataSource
--- PASS: TestVDCDataSource (87.90s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  88.453s
```

fix: testAcc Get checks from resource to datasource

---

.changelog/562.txt
internal/provider/provider.go

bump VCD API Version from 37.1 to 37.2

chore: bump VCD API Version from 37.1 to 37.2

---

.golangci.yml
internal/helpers/testsacc/testsacc.go
internal/testsacc/acctest.go
internal/testsacc/backup_datasource_test.go
internal/testsacc/backup_resource_test.go
internal/testsacc/catalog_acl_datasource_test.go
internal/testsacc/catalog_acl_resource_test.go
internal/testsacc/catalog_resource_test.go
internal/testsacc/edgegw_edgegateway_datasource_test.go
internal/testsacc/edgegw_edgegateway_resource_test.go
internal/testsacc/network_routed_resource_test.go
internal/testsacc/s3_bucket_cors_configuration_datasource_test.go
internal/testsacc/s3_bucket_cors_configuration_resource_test.go
internal/testsacc/s3_bucket_datasource_test.go
internal/testsacc/s3_bucket_resource_test.go
internal/testsacc/s3_bucket_versioning_configuration_datasource_test.go
internal/testsacc/s3_bucket_versioning_configuration_resource_test.go
internal/testsacc/tier0_vrf_datasource_test.go
internal/testsacc/vapp_org_network_resource_test.go
internal/testsacc/vapp_resource_test.go
internal/testsacc/vdc_datasource_test.go
internal/testsacc/vdc_group_datasource_test.go
internal/testsacc/vdc_group_resource_test.go
internal/testsacc/vdc_resource_test.go

FIX multi testsacc error 
```
=== RUN   TestAccBackupResource
--- PASS: TestAccBackupResource (410.92s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  411.294s
```

fix: multi testsacc error

---

internal/testsacc/acctest_datasources_test.go
internal/testsacc/catalog_datasource_test.go
internal/testsacc/catalog_vapp_template_datasource_test.go
internal/testsacc/catalogs_datasource_test.go

```
--- PASS: TestAccCatalogDataSource (19.84s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  20.142s
--- PASS: TestACCCatalogVAppTemplateDataSource (15.74s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  16.505s
--- PASS: TestACCCatalogsDataSource (14.84s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  15.373s
```

chore: refacto testsacc `_catalog` datasource

---

internal/provider/catalog/catalog_datasource.go

```
=== RUN   TestAccCatalogDataSource
2023/12/19 15:24:32 TestACC: execution ID is testacc_53cdf1a2-9e7a-11ee-88e2-7a8bf7ef3cc0
--- PASS: TestAccCatalogDataSource (22.97s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  23.486s
```

fix: nil pointer in catalog datasource

---

.changelog/575.txt
docs/data-sources/edgegateway.md
docs/resources/edgegateway.md
examples/resources/cloudavenue_edgegateway/resource.tf
internal/provider/edgegw/edgegateway_datasource.go
internal/provider/edgegw/edgegateway_resource.go
internal/provider/edgegw/edgegateway_schema.go
internal/provider/edgegw/edgegateway_types.go
internal/testsacc/edgegw_edgegateway_resource_test.go

Remove attribute `lb_enabled` for resource and datasource cloudavenue_edgegateway
```
--- PASS: TestAccEdgeGatewayResource (1375.73s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  1376.566s
```

feat!: remove `lb_enabled` attribute in edgegw resource/datasource

---

internal/provider/vrf/tier0_vrf_datasource.go
internal/provider/vrf/tier0_vrf_schema.go
internal/provider/vrf/tier0_vrf_types.go
internal/provider/vrf/tier0_vrfs_datasource.go
internal/provider/vrf/tier0_vrfs_schema.go
internal/provider/vrf/tier0_vrfs_types.go
internal/testsacc/tier0_vrf_datasource_test.go
internal/testsacc/tier0_vrfs_datasource_test.go

```
=== RUN   TestAccTier0VrfDataSource
2024/01/22 15:38:47 TestACC: execution ID is testacc_f356d0bc-b933-11ee-8f54-7a8bf7ef3cc2
--- PASS: TestAccTier0VrfDataSource (16.65s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  17.376s
=== RUN   TestAccTier0VrfsDataSource
2024/01/22 15:48:35 TestACC: execution ID is testacc_51ee825e-b935-11ee-b3e2-7a8bf7ef3cc2
--- PASS: TestAccTier0VrfsDataSource (26.51s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  27.234s
```

chore: refacto `tier0_vrf` and `tier0_vrfs` datasource to new SDK

---

.changelog/765.txt
.golangci.yml
internal/provider/edgegw/edgegateway_resource.go

Now the edgegateway use UUID instead the URN for requesting the API. 
```
==============================================================================
--- PASS: TestAccEdgeGatewayResource (585.31s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  585.847s
```

fix: get edgegateway with UUID instead URN

---

.changelog/755.txt
internal/provider/vdc/vdc_schema.go

Fix an issue with the VDC resource generate `Know after apply` on the attribute `id` if another attribute is changed.
```
--- PASS: TestAccVDCResource (359.04s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  360.128s
```

fix: known after apply on the attribute `id` in `cloudavenue_vdc`

---

.changelog/810.txt
internal/provider/vapp/common_org_network.go

```
--- PASS: TestAccOrgNetworkResource (509.56s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  510.234s
```

fix: failed to add more 1 org_network into a VApp

---

.changelog/812.txt
.pre-commit-config.yaml
docs/data-sources/vapp_isolated_network.md
docs/resources/vapp_isolated_network.md
docs/resources/vapp_org_network.md
examples/resources/cloudavenue_vapp_isolated_network/resource.tf
examples/resources/cloudavenue_vapp_org_network/import.sh
internal/provider/vapp/isolated_network_datasource.go
internal/provider/vapp/isolated_network_resource.go
internal/provider/vapp/isolated_network_schema.go
internal/provider/vapp/isolated_network_types.go
internal/testsacc/acctest_datasources_test.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/vapp_datasource_test.go
internal/testsacc/vapp_isolated_network_datasource_test.go
internal/testsacc/vapp_isolated_network_resource_test.go

```
--- PASS: TestAccVAppIsolatedNetworkResource (99.10s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  99.783s
--- PASS: TestAccVAppIsolatedNetworkDataSource (94.65s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  95.178s
```

refactor: resource/datasource `cloudavenue_vapp_isolated_network`

---

.changelog/817.txt
internal/provider/vm/vm_resource.go

```
=== RUN   TestAccOrgNetworkResource
2024/11/12 15:25:03 Starting building dependencies config
2024/11/12 15:25:03 Adding dependency cloudavenue_vdc.example
2024/11/12 15:25:03 Adding dependency cloudavenue_vapp.example
2024/11/12 15:25:03 Dependency cloudavenue_vdc.example already exists
2024/11/12 15:25:03 Adding dependency cloudavenue_network_routed.example
2024/11/12 15:25:03 Adding dependency data.cloudavenue_tier0_vrf.example
2024/11/12 15:25:03 Adding dependency cloudavenue_edgegateway.example
2024/11/12 15:25:03 Finished building dependencies config. Found 5 dependencies
2024/11/12 15:25:03 
resource "cloudavenue_vapp_org_network" "example" {
vapp_name    = cloudavenue_vapp.example.name
network_name = …
```

fix: bug vapp network not created

---

docs/resources/iam_user_saml.md
internal/provider/iam/user_saml_resource.go
internal/provider/iam/user_saml_schema.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/iam_user_datasource_test.go
internal/testsacc/iam_user_saml_resource_test.go
templates/resources/iam_user_saml.md.tmpl

```
--- PASS: TestAcciamUserSAMLResource (44.36s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  44.866s
--- PASS: TestAccIAMUserDataSource (14.08s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  15.046s
```

chore: add testsacc ress `iam_user_saml` and set to prod ready

---

.changelog/849.txt
docs/data-sources/edgegateway_app_port_profile.md
internal/provider/edgegw/app_port_profile_datasource.go
internal/provider/edgegw/app_port_profile_resource.go
internal/provider/edgegw/app_port_profile_schema.go
internal/provider/edgegw/app_port_profile_type.go
internal/testsacc/edgegw_app_port_profile_datasource_test.go

```
--- PASS: TestAccEdgeGatewayAppPortProfileResource (404.90s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  405.547s
--- PASS: TestAccEdgeGatewayAppPortProfileDataSource (1596.785s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  1596.785s
```

fix: bad ID returned in datasource app_port_profile

---

internal/testsacc/edgegw_edgegateway_resource_test.go

```
--- PASS: TestAccEdgeGatewayResource (225.46s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  225.992s
```

test: use vdcg resource instead vdc_group

---

.changelog/888.txt
docs/resources/network_isolated.md
examples/resources/cloudavenue_network_isolated/resource.tf
internal/provider/common/network/schema.go
internal/provider/network/common_network.go
internal/provider/vdc/network_isolated_resource.go
templates/resources/network_isolated.md.tmpl

```hcl
resource "cloudavenue_vdc_network_isolated" "example" {
vdc         = cloudavenue_vdc.example2.name
name        = "rsx-example-isolated-network"
description = "My isolated Org VDC network"
gateway       = "192.168.168.254"
prefix_length = 24
dns1       = "8.8.8.8"
dns2       = "8.8.4.4"
dns_suffix = "example.com"
}
moved {
from = cloudavenue_network_isolated.example
to   = cloudavenue_vdc_network_isolated.example
}
```
```
cloudavenue_vdc.example2: Refreshing state... [id=urn:vcloud:vdc:xxx]
cloudavenue_vdc_network_isolated.example: Refreshing state... [id=urn:vcloud:network:xxx]
data.cloudavenue_edgegateway.example: Read complete after 4s [id=urn:vcloud:gateway:xxx]
Terraform will perform the following actions: …
```

chore: add movestate and deprecation notice

---

.changelog/934.txt
internal/provider/vdc/vdc_datasource.go
internal/testsacc/vdc_datasource_test.go

```
--- PASS: TestAccVDCDataSource (71.01s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  71.557s
```

fix: datasource `cloudavenue_vdc` not returning storage_profiles 

---

.changelog/940.txt
internal/provider/publicip/publicip_resource.go
internal/provider/publicip/publicip_schema.go
internal/testsacc/publicip_resource_test.go

```
--- PASS: TestAccPublicIPResource (347.53s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  348.072s
```

chore: `cloudavenue_publicip` return edge name and id in tfstate

---

.changelog/875.txt
.vscode/terraform.code-snippets
internal/testsacc/iam_user_saml_resource_test.go

```
--- PASS: TestAccIAMUserSAMLResource (53.20s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  53.823s
```

fix(iam): user saml quota not correctly set

---

.changelog/993.txt
internal/provider/edgegw/edgegateway_resource.go

fix: create simultaneously edgegateway failure

---

.changelog/1022.txt
docs/resources/vdcg_security_group.md
examples/resources/cloudavenue_vdcg_security_group/resource.tf
go.mod
go.sum
internal/provider/vdcg/network_routed_resource.go
internal/provider/vdcg/security_group_resource.go
internal/provider/vdcg/security_group_schema.go
internal/testsacc/vdcg_security_group_resource_test.go

This pull request includes several enhancements and fixes for the `cloudavenue_vdcg_security_group` resource. The most important changes include improving error messages, updating documentation, adding validation for network members, and updating dependencies.
Enhancements to error messages and validation:
* [`.changelog/1022.txt`](diffhunk://#diff-2ebaa461288a6dfa27c640074c088ba58ff6f7afec185fd730dd4113dd7874d4R1-R3): Improved error message for creating a security group with an invalid network.
* [`internal/provider/vdcg/security_group_resource.go`](diffhunk://#diff-ee32c160a16434657d734044561f32afd345ea9ba2e01f03de3eee19a1044877R118-R122): Added `validateNetworks` function to validate networks in the security group during creation and update. …

chore: improve error message vdcg security group

---

.changelog/1045.txt
internal/provider/edgegw/network_routed_resource.go

This pull request includes a bug fix and a minor improvement to error handling in the `cloudavenue_edgegateway_network_routed` resource. The most important changes are:
Bug fix:
* [`.changelog/1045.txt`](diffhunk://#diff-f2ea5c8bbbfd14d70a8d4cff8a7ffc685a8e6352583fd1e2bd69f72d03c8a6cbR1-R3): Added a release note indicating that a crash caused by a nil pointer dereference in the `cloudavenue_edgegateway_network_routed` resource read operation has been fixed.
Error handling improvement:
* [`internal/provider/edgegw/network_routed_resource.go`](diffhunk://#diff-73dddf1dea18bbcfe5b7bd4b72e5bdcb7cc2e7af70f8945917af1e45e79531b8R65): Added a return statement to the `Init` function to prevent further execution after an error is encountered while retrieving the Edge Gateway.

fix: nil pointer in the `cloudavenue_edgegateway_network_routed`

---

.goreleaser.yml

This pull request includes changes to the `.goreleaser.yml` file to update the configuration for building and releasing Go projects. The most important changes include modifying the snapshot naming template and adjusting the format specification for archives.
Configuration updates:
* [`.goreleaser.yml`](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689L10-R10): Changed `name_template` to `version_template` under the `snapshot` section to better reflect the purpose of the template.
* [`.goreleaser.yml`](diffhunk://#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689L38-R38): Updated the `archives` section to specify formats using an array, which enhances flexibility and clarity in defining multiple formats.

chore: fix deprecated goreleaser notice

---

.changelog/1069.txt
docs/resources/edgegateway.md
internal/provider/edgegw/edgegateway_resource.go

This pull request addresses a known API bug related to the `bandwidth` attribute for Edge Gateways with Tier-0 VRFs of class `DEDICATED`. The changes introduce a workaround to prevent errors when setting `bandwidth` in these cases and update relevant documentation to clarify the limitation.
* Added logic in `internal/provider/edgegw/edgegateway_resource.go` to skip `bandwidth` validation and updates when the Tier-0 VRF is of class `DEDICATED`, as the API currently does not support this configuration. This includes updates in the `ModifyPlan` and `Create` methods to handle the limitation gracefully. [[1]](diffhunk://#diff-bae05ffe16d83dbf5c0fdd34caf6ab12fe93c124162d1913e51f47773ddf811bR125-R141) [[2]](diffhunk://#diff-bae05ffe16d83dbf5c0fdd34caf6ab12fe93c124162d1913e51f47773ddf811bL316-R357 …

fix: create T1 if T0 dedicated

---

.changelog/1064.txt
.changelog/1071.txt
.changelog/1073.txt
cmd/edgegateway-doc/main.go
docs/resources/edgegateway.md
internal/provider/edgegw/edgegateway_schema.go
internal/provider/edgegw/network_routed_resource.go

This pull request addresses several bug fixes and improvements for the `cloudavenue_edgegateway_network_routed` resource, including resolving deletion issues, correcting unexpected attribute changes, and updating the locking mechanism to use a more appropriate identifier. Additionally, minor code cleanups were performed in import statements.
* **Deletion Failure Fix**: Resolved an issue where deletion operations for the `cloudavenue_edgegateway_network_routed` resource failed due to a `BUSY_ENTITY` error caused by concurrent gateway updates.
* **Static IP Pool Attribute Fix**: Fixed a bug where the `static_ip_pool` attribute unexpectedly changed from `null` to an empty set during application. [[1]](diffhunk://#diff-30cbdbe18e14b3a7ffbc257f62c2a579adc482bb38e796b053ca6107a285a9a6R1-R3) …

fix: bugs #1071 #1073 #1064

---

.changelog/952.txt
docs/data-sources/edgegateway.md
docs/data-sources/edgegateways.md
docs/resources/edgegateway.md
internal/provider/edgegw/edgegateway_datasource.go
internal/provider/edgegw/edgegateway_resource.go
internal/provider/edgegw/edgegateway_schema.go
internal/provider/edgegw/edgegateway_types.go
internal/provider/edgegw/edgegateways_datasource.go
internal/provider/edgegw/edgegateways_schema.go
internal/provider/edgegw/edgegateways_types.go
internal/testsacc/edgegw_edgegateway_resource_test.go

This pull request involves significant changes to the `cloudavenue_edgegateway` resource and associated data sources in the Terraform provider for CloudAvenue. The primary focus is the removal of the deprecated `owner_type` attribute, as announced in the release v0.24.0.
* [`.changelog/952.txt`](diffhunk://#diff-be4b2376c19ce89d9ba15c50649e385a70bc70586298c98d12c6d962143423edR1-R3): Announced the removal of the `owner_type` attribute for `cloudavenue_edgegateway` and `cloudavenue_edgegateways` in the release notes.
* [`docs/data-sources/edgegateway.md`](diffhunk://#diff-89c2823abf5da92cff35fbd81d352937d7194a326a504ddb7aba94a97d975af9L37-L39): Removed the `owner_type` attribute from the documentation for the Edge Gateway data source.
* …

chore!: remove attribute owner_type for resource/datasource cloudavenue_edgegateway

---

.changelog/1081.txt
internal/provider/vdcg/network_routed_resource.go

This pull request addresses a bug fix and minor code improvements related to the `cloudavenue_vdcg_network_routed` resource. The most notable change resolves an issue where the `static_ip_pool` attribute was incorrectly set to an empty set instead of null. Additionally, a minor import adjustment was made for better code organization.
* Resolved a bug in the `cloudavenue_vdcg_network_routed` resource where the `static_ip_pool` attribute unexpectedly changed from null to an empty set during application. This was fixed by adding a condition to set `StaticIPPool` to null when no IP ranges are present. (`.changelog/1081.txt` - [[1]](diffhunk://#diff-3aa64b88215c57a582c807a8e8d98dd04d608cd7d6450a6f9cb3636a20f837a5R1-R3) `internal/provider/vdcg/network_routed_resource.go` - …

fix: vdcg_network_routed unexpectedly null to empty

---

.changelog/1130.txt
docs/data-sources/edgegateway_static_route.md
docs/resources/edgegateway_static_route.md
examples/data-sources/cloudavenue_edgegateway_static_route/data-source.tf
examples/resources/cloudavenue_edgegateway_static_route/resource_advanced.tf
go.mod
go.sum
internal/testsacc/acctest_datasources_test.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/edgegw_edgegateway_resource_test.go
internal/testsacc/edgegw_static_route_datasource_test.go
internal/testsacc/edgegw_static_route_resource_test.go
internal/testsacc/helpers.go
internal/testsacc/helpers_test.go
templates/resources/edgegateway_static_route.md.tmpl

* Updated IPsec VPN Tunnel examples to use dynamic references like `cloudavenue_publicip.example.public_ip` for local IP addresses. [[1]](diffhunk://#diff-1d913c53bb2efe513889e55aa2c9559db9fc7552cf1340abc3832b1cf2a2ad2aL24-R34) [[2]](diffhunk://#diff-1d913c53bb2efe513889e55aa2c9559db9fc7552cf1340abc3832b1cf2a2ad2aL43-R47)
* Added new example configurations for `cloudavenue_edgegateway_static_route` with advanced next-hop setups.
```
--- PASS: TestAccEdgeGatewayStaticRouteResource (868.66s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  869.156s
--- PASS: TestAccEdgeGatewayStaticRouteDataSource (351.45s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/inter …
```

refactor: TestACC datasource and resource for edgegateway static route

---

.changelog/1142.txt
.golangci.yml
internal/provider/elb/virtual_service_schema.go
internal/provider/elb/virtual_service_types.go
internal/testsacc/acctest_datasources_test.go
internal/testsacc/elb_service_engine_group_datasource_test.go
internal/testsacc/elb_service_engine_groups_datasource_test.go
internal/testsacc/elb_virtual_service_resource_test.go

This pull request addresses a bug fix, schema updates, and test adjustments for the `cloudavenue_elb_virtual_service` resource and related components. The most notable changes include fixing a bug in retrieving the `service_engine_group_name`, updating schema plan modifiers, and renaming and refactoring test files for consistency.
* Fixed an issue where the `service_engine_group_name` attribute was not retrieved correctly if set. (`.changelog/1142.txt`, [.changelog/1142.txtR1-R3](diffhunk://#diff-4ac8f637e71c85f51eb4276c78f564909b82a83325637ef32a4c365d9471ea15R1-R3))
* Updated the method call in `virtual_service_types.go` to correctly use `GetServiceEngineGroup` instead of `GetVirtualService`. (`internal/provider/elb/virtual_service_types.go`, …

fix: bug update `_elb_virtual_service` ress if service engine is set

---

.changelog/1167.txt
go.mod
go.sum
internal/provider/iam/user_saml_resource.go

This pull request addresses a bug related to the creation of SAML users in the `resource/cloudavenue_iam_user_saml` resource. It also updates a dependency to the latest version and improves error messaging for better clarity.
Bug fix:
* Fixed an issue where creating a SAML user could return an error in the `resource/cloudavenue_iam_user_saml` resource. (`.changelog/1167.txt`, [.changelog/1167.txtR1-R2](diffhunk://#diff-3ef292c3c1923ea926884fa4ecc41284d75b52c8614d7cfc584a1c9ee8d45a9aR1-R2))
Dependency update:
* Updated the `github.com/orange-cloudavenue/cloudavenue-sdk-go` dependency from version `v0.26.2` to `v0.26.3` in `go.mod`.
Error handling improvement:
* Improved the error message when user creation fails, specifying "Error creating user SAML" instead of the generic "Error creating …

fix: failed to create SAML user
