orange-cloudavenue/terraform-provider-cloudavenue

.vscode/extensions.json
.vscode/settings.json
.vscode/tasks.json
GNUmakefile

Add Golang settings, tasks and extensions recommendations

chore: add vscode configuration

---

.github/ISSUE_TEMPLATE/00_bug_report.yml
.github/ISSUE_TEMPLATE/01_documentation.yml
.github/ISSUE_TEMPLATE/02_enhancement.yml
.github/ISSUE_TEMPLATE/03_new_resource.yml
.github/ISSUE_TEMPLATE/config.yaml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

This PR contains : 
* issue templates
* PR template
* Readme
* Contributing guide

chore: add issue and PR templates

---

internal/provider/edge_gateway_datasource.go
internal/provider/edge_gateways_datasource.go
internal/provider/helper_api_errors.go

Add Helper to catch API Errors and return Terraform Diagnostic
Helper tested on 2 datasources EdgeGateway and EdgeGateways

chore: add helper to catch API Errors

---

internal/provider/edge_gateway_resource.go
internal/provider/helper_auth.go
internal/provider/helper_auth_test.go

fix: lint error

---

internal/provider/edge_gateway_resource.go
internal/provider/edge_gateway_resource_test.go
internal/provider/helper_job.go
internal/provider/public_ip_resource.go
internal/provider/vdc_resource.go

fix: create edge_gateway_resource + tests

---

docs/index.md
docs/resources/vcda_ip.md
docs/resources/vdc.md
internal/provider/vcda_ip_resource.go
internal/provider/vdc_resource.go
templates/index.md.tmpl

Improve Provider documentation with some links to Cloud Avenue documentation

docs: add Cloud Avenue documentation links

---

internal/provider/edgegw/edge_gateway_resource.go

Import Edge Gateway with Edge Name instead of ID

feat: import edge gateway by name

---

internal/tests/edge_gateway_resource_test.go

test(tf): add import test on edgegateway resource

---

internal/helpers/stringpm/README.md
internal/helpers/stringpm/default_env_var.go
internal/helpers/stringpm/default_env_var_test.go

Fixe #59 
```
ok  	github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/helpers/stringpm	0.443s
```

chore(helper): add helper stringpm `DefaultEnvVar` (#59)

---

internal/helpers/boolpm/README.md
internal/helpers/int64pm/README.md
internal/helpers/int64pm/base_default_func.go
internal/helpers/int64pm/default.go
internal/helpers/int64pm/default_env_var.go
internal/helpers/int64pm/default_env_var_test.go
internal/helpers/int64pm/default_func.go
internal/helpers/int64pm/default_func_test.go
internal/helpers/int64pm/default_test.go
internal/helpers/stringpm/README.md

Close #77 
```
=== RUN   TestDefaultEnvVarModifierPlanModifyInt64
=== RUN   TestDefaultEnvVarModifierPlanModifyInt64/null-state
=== RUN   TestDefaultEnvVarModifierPlanModifyInt64/known-plan
=== RUN   TestDefaultEnvVarModifierPlanModifyInt64/non-null-state-unknown-plan
=== RUN   TestDefaultEnvVarModifierPlanModifyInt64/unknown-config
--- PASS: TestDefaultEnvVarModifierPlanModifyInt64 (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyInt64/null-state (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyInt64/known-plan (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyInt64/non-null-state-unknown-plan (0.00s)
--- PASS: TestDefaultEnvVarModifierPlanModifyInt64/unknown-config (0.00s)
=== RUN   TestDefaultFuncModifierPlanModifyInt64
=== RUN …
```

chore(helper): add PlanModifier int64 `SetDefault...`

---

.github/workflows/test.yml
GNUmakefile

https://github.com/FrangipaneTeam/tf-doc-extractor

feat: add go generate tf-doc-extractor

---

.golangci.yml
internal/client/client.go
internal/client/client_test.go
internal/client/vmware.go
internal/provider/provider.go
internal/provider/publicip/public_ip_resource.go
internal/provider/vapp/vapp_datasource.go
internal/provider/vapp/vapp_resource.go
internal/provider/vdc/vdc_datasource.go
internal/provider/vdc/vdc_resource.go
internal/provider/vdc/vdcs_datasource.go
internal/tests/vdc_datasource_test.go
internal/tests/vdcs_datasource_test.go

Add `VDC` in var-naming check and fix all issues after apply this config

chore(lint): add `VDC` in var-naming lint

---

.vscode/terraform.code-snippets

chore: add code snippets

---

.golangci.yml
internal/provider/vrf/tier0_vrf_datasource.go

Add the pattern `VLAN` to golangci-lint

ci: add VLAN to var-naming

---

internal/client/client.go
internal/provider/provider.go

Special PR to force the API version in v37.0

chore(client): Add version API of Vcloud Client

---

docs/data-sources/vdc.md
docs/resources/vdc.md
internal/provider/vdc/base.go
internal/provider/vdc/vdc_datasource.go
internal/provider/vdc/vdc_resource.go
internal/tests/vdc/vdc_datasource_test.go
internal/tests/vdc/vdc_resource_test.go
internal/tests/vdc/vdcs_datasource_test.go

Add vDC URN ID for datasource and resource
```
❯ TF_ACC=1 go test -v -count=1 ./internal/tests/vdc
=== RUN   TestAccVDCDataSource
--- PASS: TestAccVDCDataSource (15.44s)
=== RUN   TestAccVDCGroupDataSource
--- PASS: TestAccVDCGroupDataSource (4.66s)
--- PASS: TestAccVDCResource (81.11s)
=== RUN   TestAccVDCsDataSource
--- PASS: TestAccVDCsDataSource (6.62s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vdc 107.840s
```

feat(vdc): add URN ID

---

internal/helpers/job.go
internal/provider/edgegw/edgegateway_datasource.go
internal/provider/edgegw/edgegateway_resource.go
internal/provider/edgegw/edgegateways_datasource.go
internal/provider/publicip/publicip_resource.go
internal/provider/publicip/publicips_datasource.go
internal/provider/vapp/acl_resource.go
internal/provider/vdc/vdc_datasource.go
internal/provider/vdc/vdc_resource.go
internal/provider/vdc/vdcs_datasource.go

https://dev.to/kwereutosu/the-k-i-s-s-principle-in-programming-1jfg

fix: catch defer err

---

internal/provider/catalog/catalog_resource.go
internal/tests/catalog/catalog_resource_test.go

Fixes: #171 
```
=== RUN   TestAccCatalogResource
--- PASS: TestAccCatalogResource (20.05s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/catalog     20.477s
```

fix: storage profile error

---

docs/resources/vdc_acl.md
examples/resources/cloudavenue_vdc_acl/resource.tf
internal/provider/vdc/acl_resource.go
internal/tests/vdc/acl_resource_test.go

```
❯ TF_ACC=1 go test -v -count=1  -run TestAccACLResource  ./internal/tests/vdc
=== RUN   TestAccACLResource
--- PASS: TestAccACLResource (11.22s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vdc 11.523s
```

fix(vdc): acl_resource have a missing error in return

---

GNUmakefile

Update githooks submodule that onboard a GitLeaks pre-commit hooks

feat: update githooks submodule for gitleaks

---

docs/data-sources/catalog.md
docs/resources/catalog.md
internal/provider/catalog/catalog_datasource.go
internal/provider/catalog/catalog_resource.go
internal/provider/catalog/catalog_schema.go
internal/tests/catalog/catalog_datasource_test.go
internal/tests/catalog/catalog_resource_test.go

fixe #206 
```
go test -v -count=1  -run TestAccCatalogDataSource  ./internal/tests/catalog
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/catalog     16.865s
go test -v -count=1  -run TestAccCatalogResource  ./internal/tests/catalog
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/catalog     21.888s
```

refactor: use superschema for catalog resource/datasource

---

internal/provider/common/vdc/vdc.go

feat(vdc): add superschema for vdc

---

internal/provider/catalog/catalog_datasource.go
internal/provider/catalog/catalog_resource.go
internal/provider/catalog/catalog_schema.go
internal/provider/common/schema/attribute.go
internal/provider/common/schema/bool_attribute.go
internal/provider/common/schema/int64_attribute.go
internal/provider/common/schema/list_attribute.go
internal/provider/common/schema/list_nested_attribute.go
internal/provider/common/schema/object_attribute.go
internal/provider/common/schema/schema.go
internal/provider/common/schema/set_attribute.go
internal/provider/common/schema/set_nested_attribute.go
internal/provider/common/schema/string_attribute.go
internal/provider/common/schema/timeouts_attribute.go
internal/provider/iam/role_datasource.go
internal/provider/iam/role_resource.go
internal/provider/iam/user_datasource.go
internal/provider/iam/user_resource.go
internal/provider/vm/vm_affinity_rule_resource.go

feat: add timeout in superschema

---

docs/data-sources/edgegateway.md
docs/data-sources/edgegateways.md
docs/resources/edgegateway.md
examples/resources/cloudavenue_edgegateway/resource.tf
internal/provider/common/schema/timeouts_attribute.go
internal/provider/edgegw/edgegateway_datasource.go
internal/provider/edgegw/edgegateway_resource.go
internal/provider/edgegw/edgegateway_schema.go
internal/provider/edgegw/edgegateways_datasource.go
internal/tests/edgegw/edgegateway_datasource_test.go
internal/tests/edgegw/edgegateway_resource_test.go

Add loadbalancer to the edgegateway + use superschema
All acceptance tests on edgegw ar OK

feat(edgegw): add loadbalancer

---

internal/provider/common/adminorg/admin_org.go
internal/provider/common/adminorg/edgegw.go
internal/provider/common/edgegw/edgegw.go
internal/provider/common/org/edgegw.go
internal/provider/common/org/org.go

chore: add common edgegw

---

docs/data-sources/vdc.md
docs/data-sources/vdcs.md
docs/resources/iam_user.md
docs/resources/vdc.md
internal/provider/common/schema/bool_attribute.go
internal/provider/common/schema/float64_attribute.go
internal/provider/common/schema/int64_attribute.go
internal/provider/common/schema/list_attribute.go
internal/provider/common/schema/list_nested_attribute.go
internal/provider/common/schema/object_attribute.go
internal/provider/common/schema/set_attribute.go
internal/provider/common/schema/string_attribute.go
internal/provider/vdc/vdc_datasource.go
internal/provider/vdc/vdc_resource.go
internal/provider/vdc/vdc_schema.go
internal/provider/vdc/vdcs_datasource.go
templates/data-sources/vdc.md.tmpl
templates/resources/vdc.md.tmpl

Use superschema with vdc resource and data source.
```
--- PASS: TestAccVDCResource (77.72s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vdc 77.727s
```

refactor: add superschema to vdc

---

.vscode/terraform.code-snippets

Add new snippets (Func Init) and fix old snippets

chore: vscode snippets

---

docs/data-sources/vdc.md
internal/provider/vdc/vdc_schema.go

Minor fix in vdc schema
```
❯ TF_ACC=1 go test -v -count=1 -run TestAccVDCDataSource ./internal/tests/vdc
=== RUN   TestAccVDCDataSource
--- PASS: TestAccVDCDataSource (17.45s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vdc 17.457s
```

fix: vdc superschema

---

GNUmakefile
internal/provider/iam/role_resource.go
internal/provider/vdc/acl_resource.go
internal/tests/catalog/catalog_vapp_template_datasource_test.go
internal/tests/catalog/media_datasource_test.go
internal/tests/catalog/medias_datasource_test.go
internal/tests/edgegw/edgegateway_resource_test.go
internal/tests/iam/iam_role_resource_test.go
internal/tests/network/isolated_resource_test.go
internal/tests/network/routed_resource_test.go
internal/tests/vapp/acl_resource_test.go
internal/tests/vapp/isolated_network_resource_test.go
internal/tests/vapp/org_network_resource_test.go
internal/tests/vapp/vapp_resource_test.go
internal/tests/vdc/acl_resource_test.go
internal/tests/vdc/vdc_group_datasource_test.go
internal/tests/vm/inserted_media_resource_test.go
internal/tests/vm/vm_affinity_rule_datasource_test.go
internal/tests/vm/vm_affinity_rule_resource_test.go

Optimize time execution for make generate command

chore: optimize make generate

---

internal/provider/vm/common_vm.go
internal/provider/vm/common_vm_create.go
internal/provider/vm/vm_resource.go
internal/tests/vm/vm_resource_test.go

```
TF_ACC=1 go test -v -count=1  -run TestAccVMResource  ./internal/tests/vm
=== RUN   TestAccVMResource
--- PASS: TestAccVMResource (132.50s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/vm  132.951s
```

fix: vm resource

---

templates/data-sources/catalog_media.md.tmpl
templates/data-sources/catalog_medias.md.tmpl
templates/data-sources/iam_right.md.tmpl
templates/resources/vm.md.tmpl

docs: fix subcategories

---

docs/index.md
docs/resources/vapp.md
internal/provider/catalog/media_datasource.go
internal/provider/provider.go
internal/provider/vapp/vapp_resource.go
templates/index.md.tmpl

docs: fix some docs

---

.ci/scripts/generate-changelog.sh

Fix non existing option in generate-changelog.sh

ci: fix generate option

---

docs/resources/vdc_acl.md
internal/provider/common/acl/acl.go
internal/provider/vdc/acl_resource.go
internal/provider/vdc/acl_schema.go

refactor(vdc): move cloudavenue_vdc_acl  to superschema

---

docs/resources/vapp_acl.md
internal/provider/common/vapp/vapp.go
internal/provider/vapp/acl_resource.go
internal/provider/vapp/acl_schema.go

refactor(vapp): move cloudavenue_vapp_acl to superschema

---

docs/data-sources/tier0_vrf.md
docs/data-sources/tier0_vrfs.md
internal/provider/provider.go
internal/provider/vrf/base.go
internal/provider/vrf/tier0_vrf_datasource.go
internal/provider/vrf/tier0_vrfs_datasource.go

feat(vrf): add superschema + refactor 

---

internal/provider/vcda/vcda_ip_resource.go

feat(vcda): add superschema + refactor on `vcda_ip_resource`

---

docs/data-sources/alb_pool.md
docs/resources/alb_pool.md
internal/provider/alb/pool_schema.go

Check description of `alb` (resource/datasource)

docs: Check description of `alb` resource and datasource

---

docs/resources/vapp_acl.md
docs/resources/vdc_acl.md
internal/provider/common/acl/acl.go

Check description of common `acl`

docs: Check description of common `acl`

---

docs/data-sources/edgegateway.md
docs/data-sources/edgegateways.md
docs/resources/edgegateway.md
internal/provider/edgegw/edgegateway_schema.go

Check description of `edgegateway` resource and datasource

docs: Check description of `edgegateway` resource and datasource

---

docs/data-sources/publicips.md
internal/provider/publicip/publicips_datasource.go

Check description of `publicip` resource and datasource

docs: Check description of `publicip` resource and datasource

---

docs/data-sources/vdc_group.md
internal/provider/vdc/vdc_group_datasource.go

Check description of `vdc` resource and datasource

docs: Check description of `vdc` resource and datasource

---

internal/client/admin_vdc.go
internal/client/vmware.go
internal/provider/common/adminvdc/admin_vdc.go

Add AdminVDC Client and Meta Object

chore: Add AdminVDC Client and Meta Object

---

internal/provider/vapp/acl_resource.go

fix: unlock in append diags function

---

.github/workflows/release.yml

Add dependencies between release-notes and goreleaser to download artifact

ci: add dependencies between jobs

---

.vscode/terraform.code-snippets

chore: add snippets for changelog

---

.changelog/365.txt
internal/provider/vapp/org_network_resource.go

Fixe bug in `cloudavenue_vapp_org_network`.

fix: bug in org_network_resource vapp undeploy

---

.golangci.yml
.vscode/tasks.json
GNUmakefile
README.md

- docs: improve README
- chore: improve testacc Vscode
- chore: remove deprecated linters

chore: improve README/tests/tasks

---

.github/workflows/codeql.yml

ADD CI CodeQL (Github Security recommandation)

ci: add codeql scanning

---

.github/workflows/codeql.yml

Change trigger to one time per week only

chore(script): Change action of codeQL to one time per week

---

.github/CODE_OF_CONDUCT.md

chore: Update Code Of Conduct

---

.github/CODEOWNERS

chore: update CodeOwner

---

.changelog/384.txt
docs/data-sources/catalog_medias.md
internal/provider/catalog/media_schema.go
internal/provider/catalog/medias_datasource.go
internal/provider/catalog/medias_schema.go

```
TF_ACC=1 go test -v -count=1 -timeout 600m github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/tests/catalog/medias_datasource_test.go
=== RUN   TestAccCatalogMediasDatasource
--- PASS: TestAccCatalogMediasDatasource (19.26s)
PASS
ok      command-line-arguments  19.755s
```

refactor: schema medias catalog

---

internal/provider/catalog/catalog_schema.go
internal/provider/catalog/catalog_types.go
internal/provider/catalog/catalog_vapp_template_datasource.go
internal/provider/catalog/catalog_vapp_template_schema.go
internal/provider/catalog/catalog_vapp_template_types.go
internal/provider/catalog/catalogs_datasource.go
internal/provider/catalog/catalogs_schema.go
internal/provider/catalog/catalogs_types.go
internal/provider/catalog/media_schema.go
internal/provider/catalog/media_types.go
internal/provider/catalog/medias_datasource.go
internal/provider/catalog/medias_schema.go
internal/provider/catalog/medias_types.go

chore(catalog): Refactor schema/types

chore(catalog): Refactor schema/types

---

internal/provider/iam/right_datasource.go
internal/provider/iam/right_schema.go
internal/provider/iam/right_types.go
internal/provider/iam/role_schema.go
internal/provider/iam/role_types.go
internal/provider/iam/user_schema.go
internal/provider/iam/user_types.go

chore(iam): Add schema/types

---

internal/provider/publicip/publicip_schema.go
internal/provider/publicip/publicip_types.go
internal/provider/publicip/publicips_datasource.go
internal/provider/publicip/publicips_schema.go
internal/provider/publicip/publicips_types.go

chore(publicip): Add schema/types

chore(publicip): Add schema/types

---

internal/provider/storage/profile_datasource.go
internal/provider/storage/profile_schema.go
internal/provider/storage/profile_types.go
internal/provider/storage/profiles_datasource.go
internal/provider/storage/profiles_schema.go
internal/provider/storage/profiles_types.go

chore(storage): Add schema/types

chore(storage): Add schema/types

---

cmd/types-generator/main.go
internal/provider/iam/right_datasource.go
internal/provider/iam/right_schema.go
internal/provider/iam/right_types.go
internal/tests/iam/iam_right_datasource_test.go

```
=== RUN   TestAccIamRightDatasource
--- PASS: TestAccIamRightDatasource (6.08s)
PASS
````

chore: migrate `cloudavenue_iam_right` datasource to SuperSchema/Supertypes

---

internal/provider/edgegw/app_port_profile_resource.go
internal/provider/edgegw/app_port_profile_schema.go
internal/provider/edgegw/app_port_profile_type.go
internal/provider/edgegw/edgegateway_schema.go
internal/provider/edgegw/edgegateway_types.go
internal/provider/edgegw/edgegateways_datasource.go
internal/provider/edgegw/edgegateways_schema.go
internal/provider/edgegw/edgegateways_types.go
internal/provider/edgegw/firewall_resource.go
internal/provider/edgegw/firewall_types.go
internal/tests/edgegw/edgegateway_resource_test.go

chore(edgegw): Add schema/types

chore(edgegw): Add schema/types

---

internal/provider/vdc/acl_schema.go
internal/provider/vdc/acl_types.go
internal/provider/vdc/vdc_group_datasource.go
internal/provider/vdc/vdc_group_types.go
internal/provider/vdc/vdc_schema.go
internal/provider/vdc/vdc_types.go
internal/provider/vdc/vdcs_datasource.go
internal/provider/vdc/vdcs_schema.go
internal/provider/vdc/vdcs_types.go

chore(vdc): Add schema/types

---

internal/provider/alb/pool_schema.go
internal/provider/alb/pool_types.go

chore(alb): Add types

---

internal/provider/vrf/tier0_vrf_datasource.go
internal/provider/vrf/tier0_vrf_schema.go
internal/provider/vrf/tier0_vrf_types.go
internal/provider/vrf/tier0_vrfs_datasource.go
internal/provider/vrf/tier0_vrfs_schema.go
internal/provider/vrf/tier0_vrfs_types.go

chore(vrf): Add types/schema

---

internal/provider/vcda/vcda_ip_resource.go

Fix ID format in Import func
```
=== RUN   TestAccVCDAResource
--- PASS: TestAccVCDAResource (9.90s)
PASS
ok      command-line-arguments  10.410s
```

fix: `cloudavenue_vcda_ip` ID in import

---

internal/provider/vapp/acl_schema.go
internal/provider/vapp/acl_types.go
internal/provider/vapp/isolated_network_datasource.go
internal/provider/vapp/isolated_network_resource.go
internal/provider/vapp/isolated_network_schema.go
internal/provider/vapp/isolated_network_types.go
internal/provider/vapp/vapp_schema.go
internal/provider/vapp/vapp_types.go

chore(vapp): Add schema/types

---

.github/workflows/generate.yml
.github/workflows/generate_listing.yml
.github/workflows/release.yml
.github/workflows/test.yml

ci: Add GoTests.yml

---

.github/workflows/generate_listing.yml
internal/provider/provider.go
internal/provider/provider_datasources.go
internal/provider/provider_resources.go
internal/provider/provider_schema.go
internal/provider/provider_types.go

chore: re-organize provider files

---

.github/workflows/testacc.yml

ci: Add Acceptance Tests

---

.vscode/terraform.code-snippets
docs/resources/vm_inserted_media.md
internal/provider/common/vm/vm.go
internal/provider/provider_resources.go
internal/provider/vm/inserted_media_resource.go
internal/provider/vm/inserted_media_schema.go
internal/provider/vm/inserted_media_types.go
internal/tests/vapp/vapp_resource_test.go
internal/tests/vm/inserted_media_resource_test.go
internal/tests/vm/vm_resource_test.go

The code has been tested, but there is an error is thrown at the end due to a known bug in vcloud-sdk.

chore: upgrade `cloudavenue_vm_inserted_media` to superSchema

---

GNUmakefile

Integrate terraform fmt into generate workflow

chore(ci): integrate terraform fmt into generate

---

.changelog/451.txt
docs/data-sources/edgegateway_nat_rule.md
docs/data-sources/vapp_isolated_network.md
docs/data-sources/vm.md
docs/resources/catalog.md
examples/data-sources/cloudavenue_edgegateway_nat_rule/data-source.tf
examples/data-sources/cloudavenue_vapp_isolated_network/data-source.tf
examples/data-sources/cloudavenue_vm/data-source.tf
examples/resources/cloudavenue_catalog/resource.tf
examples/resources/resource.tf

Format terraform example files / docs

chore: Format terraform example files / docs

---

.github/workflows/testacc.yml

ci: testacc enhancement

---

.github/workflows/testacc.yml

Fix Acceptance Tests to make them work with the current pr 

ci: Fix Acceptance Tests

---

.github/workflows/testacc.yml

ci: Fix testacc.yml

---

.changelog/443.txt
.github/workflows/testacc.yml
docs/data-sources/catalog_vapp_template.md
docs/data-sources/catalogs.md
internal/provider/catalog/catalog_schema.go
internal/provider/catalog/catalog_vapp_template_datasource.go
internal/provider/catalog/catalog_vapp_template_schema.go
internal/provider/catalog/catalog_vapp_template_types.go
internal/provider/catalog/catalogs_datasource.go
internal/provider/catalog/catalogs_schema.go
internal/provider/edgegw/ip_set_resource.go
internal/tests/catalog/catalog_vapp_template_datasource_test.go
internal/tests/catalog/catalogs_datasource_test.go
pkg/uuid/uuid.go
pkg/uuid/uuid_test.go

chore: migrate `cloudavenue_(catalogs/catalog_vapp_template)` to superschema

---

cmd/listing/main.go
cmd/listing/resource-ca.md

chore: Update listing

---

.changelog/481.txt
docs/resources/vdc.md
examples/resources/cloudavenue_vdc/resource.tf

docs: fix example in `cloudavenue_vdc` resource

---

internal/provider/edgegw/nat_rule_resource.go

fix: error message in ImportFunc (#482)

---

docs/data-sources/edgegateways.md
internal/provider/edgegw/edgegateways_datasource.go
internal/provider/edgegw/edgegateways_schema.go
internal/provider/edgegw/edgegateways_types.go
internal/tests/edgegw/edgegateways_datasource_test.go

chore: migrate `cloudavenue_edgegateways` datasource to superschema

---

.changelog/500.txt
go.mod
go.sum
internal/provider/edgegw/nat_rule_types.go
internal/provider/edgegw/static_route_types.go
internal/provider/edgegw/vpn_ipsec_resource.go
internal/provider/edgegw/vpn_ipsec_types.go
internal/provider/network/dhcp_binding_resource.go
internal/provider/network/dhcp_binding_types.go

bump FrangipaneTeam/terraform-plugin-framework-superschema to v1.5.3

chore: bump FrangipaneTeam/terraform-plugin-framework-superschema 

---

cmd/types-generator/main.go

chore: improve types generator

---

internal/testsacc/acctest.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/catalog_acl_datasource_test.go
internal/testsacc/catalog_acl_resource_test.go
internal/testsacc/catalog_resource_test.go
internal/testsacc/iam_user_resource_test.go

Refactor catalog acceptances tests
Due #489 
Block #495

test: Catalog acceptances tests refactor

---

go.mod
go.sum
internal/helpers/testsacc/template.go
internal/helpers/testsacc/testsacc.go
internal/testsacc/acctest.go
internal/testsacc/acctest_datasources_test.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/catalog_resource_test.go
internal/testsacc/edgegw_edgegateway_resource_test.go
internal/testsacc/tier0_vrf_datasource_test.go
internal/testsacc/vdc_resource_test.go

add generate template for testsacc

feat: add generate template for testsacc

---

.changelog/524.txt
docs/resources/vdc.md
internal/provider/vdc/vdc_schema.go

-->
test with terraform cli, because #528

fix: Bug VDC attributes unchangeables

---

internal/provider/vapp/org_network_resource.go

fix: add `vapp_id` attribut in `cloudavenue_vapp_org_network`

---

.changelog/524.txt

fix: changelog message for PR524

---

.changelog/533.txt
docs/resources/vdc.md
docs/resources/vm_disk.md
go.mod
go.sum
internal/provider/vdc/vdc_schema.go

chore: add generate docs for planmodifier RequireReplaceIf

---

internal/helpers/job.go
internal/helpers/testsacc/testsacc.go
internal/provider/vdc/vdc_resource.go
internal/testsacc/vdc_group_resource_test.go
internal/testsacc/vdc_resource_test.go

Fixe #528 
```
--- PASS: TestAccVDCResource (54.38s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  54.883s
```

chore: testsacc support TFAdvanced

---

internal/provider/backup/backup_datasource.go

fix: resource name for stats

---

.github/workflows/generate.yml
.github/workflows/lint.yml
.golangci.yml
internal/provider/provider.go
internal/testsacc/alb_pool_datasource_test.go
internal/testsacc/alb_pool_resource_test.go
internal/testsacc/edgegw_edgegateways_datasource_test.go
internal/testsacc/network_isolated_resource_test.go
internal/testsacc/network_routed_datasource_test.go
internal/testsacc/profile_datasource_test.go
internal/testsacc/profiles_datasource_test.go
internal/testsacc/vapp_acl_resource_test.go
internal/testsacc/vapp_isolated_network_datasource_test.go
internal/testsacc/vapp_isolated_network_resource_test.go
internal/testsacc/vapp_org_network_datasource_test.go
internal/testsacc/vdc_acl_resource_test.go
internal/testsacc/vdcs_datasource_test.go
internal/testsacc/vm_datasource_test.go
internal/testsacc/vm_security_tag_resource_test.go
pkg/uuid/uuid.go
pkg/uuid/uuid_test.go

fix: errors lint goconst

---

.devcontainer/.terraformrc
.devcontainer/Dockerfile
.devcontainer/devcontainer.json

chore: add devcontainer

---

.github/dependabot.yml

Dependabot settings for AWS dependency

chore: add dependabot settings for AWS dependency

---

.changelog/641.txt
internal/provider/s3/bucket_acl_resource.go
internal/provider/s3/bucket_acl_types.go

Fix #641 
```
--- PASS: TestAccS3BucketACLResource (61.87s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  62.399s
```

fix: `_s3_bucket_acl` catch error when bucket read return a error

---

.changelog/639.txt
docs/resources/edgegateway.md
docs/resources/edgegateway_firewall.md
internal/provider/edgegw/edgegateways_datasource.go
internal/provider/edgegw/edgegateways_schema.go
internal/provider/edgegw/edgegateways_types.go
internal/testsacc/acctest_datasources_test.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/common.go
internal/testsacc/edgegw_dhcp_forwarding_resource_test.go
internal/testsacc/edgegw_edgegateway_resource_test.go
internal/testsacc/edgegw_edgegateways_datasource_test.go
internal/testsacc/edgegw_firewall_datasource_test.go
internal/testsacc/edgegw_firewall_resource_test.go
internal/testsacc/vdc_group_resource_test.go
internal/testsacc/vdc_resource_test.go
templates/resources/edgegateway.md.tmpl
templates/resources/edgegateway_firewall.md.tmpl

```
--- PASS: TestAccVDCGroupResource (175.26s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  175.811s
--- PASS: TestAccEdgeGatewayResource (832.00s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  832.563s
--- PASS: TestAccEdgeGatewayDataSource (300.48s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  300.810s
--- PASS: TestAccEdgeGatewaysDataSource (253.64s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  254.129s
--- PASS: TestAccEdgeGatewayFirewallDataSource (293.88s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/int …
```

chore: refacto test ACC edgegw

---

internal/helpers/testsacc/testsacc.go
internal/testsacc/acctest.go

This test not working before fixing the problem
```
=== RUN   TestAccCatalogDataSource
--- PASS: TestAccCatalogDataSource (23.53s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  24.244s
```

fix: testsacc tools dependency

---

docs/data-sources/catalog.md
examples/data-sources/cloudavenue_catalog/data-source.tf

docs: fix example in catalog datasource

---

.changelog/667.txt
docs/resources/vm_disk.md
templates/resources/vm_disk.md.tmpl

docs: improve internal disk example in _vm_disks resource

---

.vscode/terraform.code-snippets
GNUmakefile
internal/provider/iam/role_resource.go
internal/provider/vdc/acl_resource.go
internal/testsacc/catalog_media_datasource_test.go
internal/testsacc/catalog_medias_datasource_test.go
internal/testsacc/edgegw_app_port_profile_resource_test.go
internal/testsacc/edgegw_edgegateway_resource_test.go
internal/testsacc/edgegw_security_group_resource_test.go
internal/testsacc/iam_role_resource_test.go
internal/testsacc/network_isolated_datasource_test.go
internal/testsacc/network_isolated_resource_test.go
internal/testsacc/network_routed_datasource_test.go
internal/testsacc/profile_datasource_test.go
internal/testsacc/profiles_datasource_test.go
internal/testsacc/vapp_acl_resource_test.go
internal/testsacc/vapp_isolated_network_datasource_test.go
internal/testsacc/vapp_isolated_network_resource_test.go
internal/testsacc/vapp_org_network_datasource_test.go
internal/testsacc/vdc_acl_resource_test.go
internal/testsacc/vm_affinity_rule_datasource_test.go
internal/testsacc/vm_security_tag_resource_test.go

chore: remove tf-doc-extractor

---

internal/provider/s3/bucket_policy_resource.go
internal/provider/s3/bucket_policy_types.go

fix: timeout `s3/bucket_policy` resource

---

.changelog/680.txt
.changelog/712.txt
docs/resources/s3_bucket_policy.md
examples/resources/cloudavenue_s3_bucket_policy/resource.tf

docs: fix wrong documentation

---

.changelog/715.txt
internal/provider/provider.go

fix: init client by tf config file

---

internal/helpers/testsacc/README.md
internal/helpers/testsacc/config-name.go
internal/helpers/testsacc/list-of-dependencies.go
internal/helpers/testsacc/model.go
internal/helpers/testsacc/resource-config.go
internal/helpers/testsacc/template.go
internal/helpers/testsacc/testsacc.go
internal/provider/edgegw/dhcp_forwarding_resource.go
internal/testsacc/acctest.go
internal/testsacc/acctest_datasources_test.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/backup_datasource_test.go
internal/testsacc/backup_resource_test.go
internal/testsacc/catalog_acl_datasource_test.go
internal/testsacc/catalog_acl_resource_test.go
internal/testsacc/edgegw_dhcp_forwarding_datasource_test.go
internal/testsacc/edgegw_dhcp_forwarding_resource_test.go
internal/testsacc/edgegw_edgegateway_datasource_test.go
internal/testsacc/edgegw_edgegateway_resource_test.go
internal/testsacc/edgegw_edgegateways_datasource_test.go
internal/testsacc/iam_user_datasource_test.go
internal/testsacc/iam_user_resource_test.go
internal/testsacc/s3_user_datasource_test.go

```
--- PASS: TestAccIAMUserResource (27.76s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  28.755s
--- PASS: TestAccIAMUserDataSource (13.78s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  14.932s
--- PASS: TestAccCatalogACLResource (49.80s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  50.683s
--- PASS: TestAccEdgeGatewayDhcpForwardingResource (466.78s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  467.575s
```

chore: improve testsacc

---

.changelog/736.txt
docs/index.md
templates/index.md.tmpl

fix: env vars documentation

---

.changelog/741.txt
internal/provider/vm/vm_disk_resource.go

fix: cusom bustype `_vm_disk` resource

---

.changelog/751.txt
internal/provider/publicip/publicip_resource.go

fix: bug public_ip

---

.changelog/735.txt
docs/resources/vdc.md
internal/provider/vdc/vdc_resource.go
templates/resources/vdc.md.tmpl

Add workaround for complex validation system that is incompatible with the Terraform module.

chore: add workaround to use VDC resource in terraform module

---

internal/provider/s3/bucket_lifecycle_configuration_types.go

chore: go simple for S3.Tag len

---

.changelog/784.txt
.golangci.yml
CHANGELOG.md
internal/client/client_test.go
pkg/utils/utils.go

790 bug golang ci lint

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitmodules
.pre-commit-config.yaml
CHANGELOG.md
GNUmakefile
README.md

chore: Removed submodule

---

.changelog/818.txt
internal/provider/edgegw/ip_set_resource.go
internal/provider/edgegw/ip_set_schema.go
internal/provider/edgegw/ip_set_types.go
internal/testsacc/acctest_datasources_test.go
internal/testsacc/acctest_resources_test.go
internal/testsacc/edgegw_ip_set_datasource_test.go
internal/testsacc/edgegw_ip_set_resource_test.go

```
--- PASS: TestAccEdgeGatewayIPSetResource (1194.86s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  1195.557s
--- PASS: TestAccEdgeGatewayIPSetDataSource (632.51s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  633.217s
```

fix: edgegw_ip_set with VDCGroup return nil pointer

---

CONTRIBUTING.md
README.md

chore: improve README and CONTRIBUTING

---

.changelog/851.txt
docs/resources/publicip.md
examples/resources/cloudavenue_publicip/import.sh

docs: fix bad import example

---

.changelog/861.txt
docs/data-sources/vdc_group.md
docs/resources/vdc_group.md
go.mod
go.sum
internal/provider/vdc/vdc_group_datasource.go
internal/provider/vdc/vdc_group_resource.go
internal/provider/vdc/vdc_group_schema.go
internal/provider/vdc/vdc_group_schema_test.go
internal/provider/vdcg/vdcg_resource.go
internal/testsacc/vdcg_resource_test.go
templates/resources/vdc_group.md.tmpl

Add deprecation message and add `move` state guide. 

chore!: add deprecation for `cloudavenue_vdc_group`

---

.changelog/886.txt
docs/data-sources/network_isolated.md
docs/data-sources/vdc_group.md
docs/resources/network_isolated.md
docs/resources/vdc_group.md
go.mod
go.sum
internal/provider/common/network/schema.go
internal/provider/vdc/vdc_group_schema.go

chore: add deprecation notice

---

.changelog/756.txt
internal/provider/common/vm/internal_disk.go
internal/testsacc/vm_disk_resource_test.go

fix: `cloudavenue_vm_disk` bus_type not correctly set

---

.changelog/945.txt
internal/provider/common/vm/internal_disk.go
internal/provider/vm/vm_disk_resource.go

fix: `_vm_disk` bus type SCSI & bus number not correctly set

---

.github/workflows/generate.yml

fix: CI generate

---

.changelog/992.txt
docs/resources/vdc.md
go.mod
internal/provider/vdc/vdc_resource.go
internal/testsacc/vdc_resource_test.go
templates/resources/vdc.md.tmpl

```
--- PASS: TestAccVDCResource (375.44s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  376.000s
```

chore: improve VDC validation

---

Taskfile.yml

chore: improve taskfile for testsacc

---

.changelog/1021.txt
docs/data-sources/edgegateway_security_group.md
docs/data-sources/vdcg_network_routed.md
docs/resources/edgegateway_security_group.md
docs/resources/vdcg_network_routed.md
internal/provider/edgegw/network_routed_resource.go
internal/provider/edgegw/security_group_resource.go
internal/provider/edgegw/security_group_schema.go
internal/testsacc/edgegw_network_routed_resource_test.go
internal/testsacc/edgegw_security_group_resource_test.go
internal/testsacc/vdcg_network_routed_resource_test.go

```
--- PASS: TestAccEdgeGatewaySecurityGroupResource (583.49s)
PASS
ok      github.com/orange-cloudavenue/terraform-provider-cloudavenue/internal/testsacc  584.130s
```

feat: add validation edge_security_group

---

.changelog/1020.txt
docs/data-sources/network_routed.md
docs/resources/network_routed.md
examples/resources/cloudavenue_network_routed/import.sh
examples/resources/cloudavenue_network_routed/resource.tf
internal/provider/edgegw/network_routed_resource.go
internal/provider/network/routed_datasource.go
internal/provider/network/routed_resource.go
internal/provider/network/routed_schema.go
internal/provider/network/routed_types.go
templates/resources/network_routed.md.tmpl

chore: add deprecation notice for ress/data network routed
